#:project ../Novap.JsonRepair/Novap.JsonRepair.csproj

using System.Diagnostics;
using System.Text;
using Novap.JsonRepair;

Console.OutputEncoding = Encoding.UTF8;

// ══════════════════════════════════════════════════════════════
//  Novap.JsonRepair 性能基准测试
//  用法:  dotnet run -c Release examples/BenchRepair.cs
//         dotnet run -c Release examples/BenchRepair.cs -- --append
//           (追加到已有报告，用于对比优化前后)
// ══════════════════════════════════════════════════════════════

const int WarmupIterations = 100;
const int BenchmarkIterations = 5000;
bool appendMode = args.Contains("--append");

// ── 测试场景定义 ──────────────────────────────────────────────

var scenarios = new (string Name, string Input)[]
{
    ("ValidJson (fast path)",
     """{"name":"Alice","age":30,"active":true,"tags":["admin","user"],"address":{"city":"Shanghai","zip":"200000"}}"""),

    ("ValidJson (large payload)",
     """{"users":[{"id":1,"name":"Alice","email":"alice@example.com","scores":[95,87,92],"meta":{"active":true,"role":"admin"}},{"id":2,"name":"Bob","email":"bob@example.com","scores":[78,85,90],"meta":{"active":true,"role":"user"}},{"id":3,"name":"Charlie","email":"charlie@example.com","scores":[88,92,76],"meta":{"active":false,"role":"user"}},{"id":4,"name":"Dave","email":"dave@example.com","scores":[65,70,80],"meta":{"active":true,"role":"moderator"}},{"id":5,"name":"Eve","email":"eve@example.com","scores":[99,98,97],"meta":{"active":true,"role":"admin"}}]}"""),

    ("SingleQuotes + TrailingComma",
     "{'name': 'Alice', 'age': 30, 'active': true,}"),

    ("UnquotedKeys",
     "{name: 'Alice', age: 30, city: 'Shanghai'}"),

    ("MissingBrackets",
     """{"name":"Eve","items":["a","b","c","d"  """),

    ("MarkdownFenced",
     """
     Here is the JSON response:
     ```json
     {"name":"Bob","age":25,"verified":true}
     ```
     Hope this helps!
     """),

    ("PythonConstants",
     """{"name": "Alice", "active": True, "score": None, "verified": False}"""),

    ("JsonWithComments",
     """
     {
         // User info
         "name": "Alice",
         /* Age field */
         "age": 30,
         "tags": ["admin", "user"] // tags
     }
     """),

    ("UnquotedStrings (array)",
     "[hello, world, foo, bar, baz]"),

    ("MixedProblems",
     """
     // response
     {name: 'Alice', items: ['a', 'b', 'c',], active: True, score: None}
     """),

    ("LargeMalformed (10 users)",
     """
     ```json
     {
         // Generated by LLM
         users: [
             {name: 'Alice', age: 30, tags: ['admin', 'user',], active: True},
             {name: 'Bob', age: 25, tags: ['user',], active: True},
             {name: 'Charlie', age: 35, tags: ['moderator', 'admin',], active: False},
             {name: 'Dave', age: 28, tags: ['user', 'beta',], active: True},
             {name: 'Eve', age: 32, tags: ['admin',], active: None},
             {name: 'Frank', age: 40, tags: ['user', 'premium',], active: True},
             {name: 'Grace', age: 22, tags: ['user',], active: True},
             {name: 'Hank', age: 45, tags: ['admin', 'user',], active: False},
             {name: 'Ivy', age: 29, tags: ['user', 'beta',], active: True},
             {name: 'Jack', age: 38, tags: ['moderator',], active: True}
         ],
         total: 10
     ```
     """),
};

// ── 收集结果 ──────────────────────────────────────────────────

var results = new List<(string Name, double Avg, double Min, double P50, double P95, double P99, double AllocKB)>();

Console.WriteLine("═══════════════════════════════════════════════════════════════════════════════════");
Console.WriteLine("  Novap.JsonRepair Performance Benchmark");
Console.WriteLine("  Warmup: " + WarmupIterations + "  |  Iterations: " + BenchmarkIterations);
Console.WriteLine("═══════════════════════════════════════════════════════════════════════════════════");
Console.WriteLine();
Console.WriteLine("Scenario".PadRight(42) + "Avg(us)".PadLeft(9) + "Min(us)".PadLeft(9)
    + "P50(us)".PadLeft(9) + "P95(us)".PadLeft(9) + "P99(us)".PadLeft(9) + "Alloc/KB".PadLeft(10));
Console.WriteLine(new string('-', 103));

foreach (var (name, input) in scenarios)
{
    for (int i = 0; i < WarmupIterations; i++)
        JsonRepairer.Repair(input);

    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
    long memBefore = GC.GetTotalAllocatedBytes(true);

    var timings = new double[BenchmarkIterations];
    var sw = Stopwatch.StartNew();

    for (int i = 0; i < BenchmarkIterations; i++)
    {
        sw.Restart();
        JsonRepairer.Repair(input);
        sw.Stop();
        timings[i] = sw.Elapsed.TotalMicroseconds;
    }

    long memAfter = GC.GetTotalAllocatedBytes(true);
    double allocKB = (double)(memAfter - memBefore) / BenchmarkIterations / 1024;

    Array.Sort(timings);
    double avg = timings.Average();
    double min = timings[0];
    double p50 = timings[timings.Length / 2];
    double p95 = timings[(int)(timings.Length * 0.95)];
    double p99 = timings[(int)(timings.Length * 0.99)];

    results.Add((name, avg, min, p50, p95, p99, allocKB));

    Console.WriteLine(name.PadRight(42)
        + avg.ToString("F2").PadLeft(9) + min.ToString("F2").PadLeft(9)
        + p50.ToString("F2").PadLeft(9) + p95.ToString("F2").PadLeft(9)
        + p99.ToString("F2").PadLeft(9) + allocKB.ToString("F2").PadLeft(10));
}

// ── 输出到 Markdown 文件 ──────────────────────────────────────

var projectRoot = Environment.CurrentDirectory;
var reportDir = Path.Combine(projectRoot, "examples", "data", "report");
Directory.CreateDirectory(reportDir);
var reportPath = Path.Combine(reportDir, "benchmark-results.md");

var sb = new StringBuilder();

if (appendMode && File.Exists(reportPath))
{
    // 追加模式：读取已有内容，追加新结果
    sb.Append(File.ReadAllText(reportPath));
    sb.AppendLine();
    sb.AppendLine("---");
    sb.AppendLine();
}

sb.AppendLine("# Novap.JsonRepair Benchmark Results");
sb.AppendLine();
sb.AppendLine("- **Date**: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
sb.AppendLine("- **Runtime**: " + System.Runtime.InteropServices.RuntimeInformation.RuntimeIdentifier);
sb.AppendLine("- **Framework**: " + System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription);
sb.AppendLine("- **Warmup**: " + WarmupIterations + "  |  **Iterations**: " + BenchmarkIterations);
sb.AppendLine();
sb.AppendLine("| Scenario | Avg (us) | Min (us) | P50 (us) | P95 (us) | P99 (us) | Alloc (KB) |");
sb.AppendLine("|:---------|--------:|--------:|--------:|--------:|--------:|-----------:|");
foreach (var r in results)
{
    sb.AppendLine("| " + r.Name + " | " + r.Avg.ToString("F2") + " | " + r.Min.ToString("F2")
        + " | " + r.P50.ToString("F2") + " | " + r.P95.ToString("F2")
        + " | " + r.P99.ToString("F2") + " | " + r.AllocKB.ToString("F2") + " |");
}
sb.AppendLine();

File.WriteAllText(reportPath, sb.ToString());

Console.WriteLine();
Console.WriteLine("Report saved -> " + Path.GetFullPath(reportPath));
if (appendMode) Console.WriteLine("  (appended to previous results)");
Console.WriteLine();
Console.WriteLine("Done.");
